[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
playground = "DyPR6RSYC1DNUGFEk3johQ3i5tsRQfYuMbeubxoiK6xX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
client = "yarn run ts-node app/index.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
