[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
playground = "BVynmyfz1nEjVr8825CwADZxQoXnnesN8ujhyHDqvUy8"

[registry]
url = "https://api.apr.dev"
# url = "http://127.0.0.1:8899"

[provider]
cluster = "Devnet"
# cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
client = "yarn run ts-node app/index.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
